### PR TITLE
Run CSV tests in CI

### PR DESCRIPTION
**Pull request by ilayaraja89**

### CODE REVIEW

**Comment by ilayaraja89** [comment]
@sj I don't know how to run the CSV tests in Heroku app post deployment ? Should I add Heroku CI for this purpose ? Do you have any thoughts ?

**Comment by sudhirj** [comment]
No need yet - can just run them manually for now. They do run as part of the regular `go test` using a test server, right?

**Comment by ilayaraja89** [comment]
Yes, they run in CI using httptest server. But using a separate script, not using `go test`

**Comment by sudhirj** [comment]
Can run with a default load factor (3?) as a regular test as well. That should be enough to make sure things are working on the regular build.

**Comment by ilayaraja89** [comment]
@anuradhag Can you review this PR ?

**Pull request merged**
